Repository uiowaSEP2024/001_DisAv, pull requests merged in 2024-02, with the labels that each got.

#50 ENH: backend setup
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/testing.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  extension/public/index.html
  extension/public/manifest.json
  extension/src/App.css
  extension/src/index.css
  mobile/app.json
  server/babel.config.json
  server/index.js
  server/jest.config.mjs
  server/models/UsersModel.js
  server/package.json
  server/routes/AuthRoute.js
  server/routes/UserRoutes.js
  server/tests/UserModel.test.js
  server/tests/authRoutes.test.js
  web/public/index.html
  web/src/components/__tests__/navbar.test.js
  web/src/index.css
  web/src/styles/homepage.css
  web/src/styles/navbar.css
Labels: enhancement, testing, Difficult

#52 Adnane login 2
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/components/Dashboard.js
  web/src/components/Login.js
  web/src/components/__tests__/dashboard.test.js
  web/src/components/__tests__/login.test.js
  web/src/components/__tests__/navbar.test.js
  web/src/styles/dashboard.css
Labels: enhancement, testing, Tedious

#56 Bens branch
  .eslintrc
  .gitignore
  .idea/.gitignore
  .idea/001_DisAv.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  babel.config.js
  extension/package-lock.json
  extension/yarn.lock
  mobile/App.js
  mobile/__mocks__/@react-navigation/stack.js
  mobile/__mocks__/react-native-reanimated.js
  mobile/__mocks__/react-native/Libraries/Animated/src/Animated.js
  mobile/__tests__/screens/App.test.js
  mobile/__tests__/screens/ForgotPassword.test.js
  mobile/__tests__/screens/Home.test.js
  mobile/__tests__/screens/Login.test.js
  mobile/__tests__/screens/Rewards.test.js
  mobile/__tests__/screens/Settings.test.js
  mobile/__tests__/screens/SignUp.test.js
  mobile/babel.config.js
  mobile/coverage/clover.xml
  mobile/coverage/coverage-final.json
  mobile/coverage/lcov-report/base.css
  mobile/coverage/lcov-report/block-navigation.js
  mobile/coverage/lcov-report/favicon.png
  mobile/coverage/lcov-report/index.html
  mobile/coverage/lcov-report/mobile/App.js.html
  mobile/coverage/lcov-report/mobile/AppNavigator.js.html
  mobile/coverage/lcov-report/mobile/index.html
  mobile/coverage/lcov-report/mobile/index.js.html
  mobile/coverage/lcov-report/mobile/metro.config.js.html
  mobile/coverage/lcov-report/mobile/screens/ForgotPassword.js.html
  mobile/coverage/lcov-report/mobile/screens/Home.js.html
  mobile/coverage/lcov-report/mobile/screens/Login.js.html
  mobile/coverage/lcov-report/mobile/screens/Rewards.js.html
  mobile/coverage/lcov-report/mobile/screens/Settings.js.html
  mobile/coverage/lcov-report/mobile/screens/SignUp.js.html
  mobile/coverage/lcov-report/mobile/screens/index.html
  mobile/coverage/lcov-report/prettify.css
  mobile/coverage/lcov-report/prettify.js
  mobile/coverage/lcov-report/sort-arrow-sprite.png
  mobile/coverage/lcov-report/sorter.js
  mobile/coverage/lcov.info
  mobile/package.json
  mobile/screens/Home.js
  mobile/screens/Login.js
  mobile/screens/SignUp.js
  package.json
Labels: enhancement, testing, Difficult

#58 ENH: Adding mobile testing workflow
  .github/workflows/testing.yml
Labels: testing, Simple

#59 Web: Account creation
  package-lock.json
  package.json
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/components/Navbar.js
  web/src/components/Signup.js
  web/src/components/__tests__/signup.test.js
  web/src/styles/signup.css
Labels: bug, enhancement, testing

#82 ENH: API for updating user preferences
  server/models/UsersModel.js
  server/routes/UserRoutes.js
  server/tests/UserModel.test.js
  server/tests/UserRoutes.test.js
  server/tests/authRoutes.test.js
Labels: enhancement

#83 Mobile welcome
  mobile/__tests__/screens/Home.test.js
  mobile/__tests__/screens/Login.test.js
  mobile/components/Alert.js
  mobile/coverage/clover.xml
  mobile/coverage/coverage-final.json
  mobile/coverage/lcov-report/index.html
  mobile/coverage/lcov-report/mobile/App.js.html
  mobile/coverage/lcov-report/mobile/AppNavigator.js.html
  mobile/coverage/lcov-report/mobile/index.html
  mobile/coverage/lcov-report/mobile/screens/ForgotPassword.js.html
  mobile/coverage/lcov-report/mobile/screens/Home.js.html
  mobile/coverage/lcov-report/mobile/screens/Login.js.html
  mobile/coverage/lcov-report/mobile/screens/Rewards.js.html
  mobile/coverage/lcov-report/mobile/screens/Settings.js.html
  mobile/coverage/lcov-report/mobile/screens/SignUp.js.html
  mobile/coverage/lcov-report/mobile/screens/index.html
  mobile/coverage/lcov.info
  mobile/screens/Home.js
  server/routes/UserRoutes.js
Labels: enhancement, testing, Difficult

#87 ENH: Extension login
  .eslintignore
  .github/workflows/testing.yml
  babel.config.js
  extension/.eslintrc.json
  extension/__mocks__/chromeMock.js
  extension/__mocks__/styleMock.js
  extension/babel.config.js
  extension/jest.config.js
  extension/jest.setup.js
  extension/package.json
  extension/public/background.js
  extension/public/contentScript.js
  extension/public/manifest.json
  extension/src/App.css
  extension/src/App.js
  extension/src/App.test.js
  extension/src/__tests__/App.test.js
  extension/yarn.lock
  web/src/components/Login.js
Labels: enhancement, Difficult

#89 Preference update on sign up
  .eslintignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/test-template.md
  .gitignore
  extension/__mocks__/chromeMock.js
  extension/babel.config.js
  extension/jest.config.js
  extension/jest.setup.js
  extension/src/__tests__/App.test.js
  web/__mocks__/fileMock.js
  web/__mocks__/react-toastify.js
  web/__mocks__/styleMock.js
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/components/AuthContext.js
  web/src/components/Dashboard.js
  web/src/components/Login.js
  web/src/components/Navbar.js
  web/src/components/Preference.js
  web/src/components/Signup.js
  web/src/components/__tests__/app.test.js
  web/src/components/__tests__/dashboard.test.js
  web/src/components/__tests__/login.test.js
  web/src/components/__tests__/preference.test.js
  web/src/components/__tests__/signup.test.js
  web/src/index.js
  web/src/styles/dashboard.css
  web/src/styles/preference.css
Labels: bug, enhancement, testing

#92 Improve web code coverage
  .eslintignore
  web/src/App.js
  web/src/components/Login.js
  web/src/components/Navbar.js
  web/src/components/Preference.js
  web/src/components/Signup.js
  web/src/components/__tests__/app.test.js
  web/src/components/__tests__/login.test.js
  web/src/components/__tests__/preference.test.js
  web/src/logo.svg
Labels: testing, Tedious

#93 Backend fill out preferences
  server/models/UsersModel.js
  server/routes/UserRoutes.js
  server/tests/UserRoutes.test.js
Labels: enhancement, testing, Not difficult

#94 Fill in and Update Frequency of Tasks
  web/src/components/Preference.js
  web/src/components/__tests__/preference.test.js
Labels: enhancement, testing

#96 Fixing crash on login
  web/src/components/Login.js
Labels: bug, Simple

#125 Adding Task model and routes
  server/index.js
  server/models/TaskModel.js
  server/models/UsersModel.js
  server/routes/TaskRoutes.js
  server/routes/UserRoutes.js
  server/tests/TaskModel.test.js
  server/tests/TaskRoutes.test.js
  server/tests/UserRoutes.test.js
  server/tests/authRoutes.test.js
  web/src/components/Dashboard.js
Labels: enhancement, Tedious

#127 Filling work and reading preferences
  web/src/components/Preference.js
  web/src/components/__tests__/preference.test.js
Labels: enhancement, testing, Simple
