Repository uiowaSEP2024/001_DisAv, pull requests merged in 2024-03, with the labels that each got.

#130 get requests from query instead of body & Extension countdown
  .github/workflows/testing.yml
  extension/package.json
  extension/src/App.css
  extension/src/App.js
  extension/src/__tests__/App.test.js
  extension/src/components/CountdownTimer.js
  extension/yarn.lock
  server/models/UsersModel.js
  server/routes/TaskRoutes.js
  server/routes/UserRoutes.js
  server/tests/TaskModel.test.js
  server/tests/TaskRoutes.test.js
Labels: bug

#132 FIX: Fixed id parameter in task routes
  server/routes/TaskRoutes.js
Labels: bug

#129 Rewards page, reward history and reward shop
  web/src/App.js
  web/src/components/RewardHistory.js
  web/src/components/Rewards.js
  web/src/components/Shop.js
  web/src/components/__tests__/rewardhistory.test.js
  web/src/components/__tests__/rewards.test.js
  web/src/components/__tests__/shop.test.js
  web/src/index.js
  web/src/styles/rewards.css
Labels: enhancement, testing, Tedious

#133 ENH: Update server tests
  .github/workflows/testing.yml
  server/package.json
  server/routes/UserRoutes.js
  server/tests/TaskRoutes.test.js
  server/tests/UserRoutes.test.js
  server/tests/authRoutes.test.js
Labels: bug, Difficult

#135 Tasks page feature implementation (Break Task)
  .gitignore
  web/package.json
  web/src/App.js
  web/src/assets/coffee.mp4
  web/src/assets/fire.mp4
  web/src/components/TaskBreak.js
  web/src/components/Tasks.js
  web/src/components/__tests__/tasks.test.js
  web/src/styles/tasks.css
Labels: enhancement, testing, Simple

#139 Page navigation security patch
  web/src/App.js
  web/src/components/AuthContext.js
  web/src/components/Navbar.js
  web/src/components/ProtectedRoute.js
Labels: enhancement, Simple

#167 Display the user's book preference
  web/src/components/BookCard.js
  web/src/components/ProgressBar.js
  web/src/components/ReadTask.js
  web/src/components/__tests__/bookcard.test.js
  web/src/components/__tests__/progressbar.test.js
  web/src/components/__tests__/readtask.test.js
  web/src/styles/ReadTask.css
  web/src/styles/bookcard.css
  web/src/styles/progressbar.css
Labels: enhancement, Not difficult

#168 Book detail pop up
  web/package.json
  web/src/components/BookCard.js
  web/src/components/BookDetail.js
  web/src/components/ReadTask.js
  web/src/components/__tests__/bookdetail.test.js
  web/src/styles/bookdetail.css
Labels: enhancement, testing
